import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import ClientProvider from "@/components/Provider";
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="bg-secondary_background">
                <ClientProvider>
                    <div className="max-w-[1200px] mx-auto min-h-screen">
                        <Navbar />
                        {children}
                    </div>
                </ClientProvider>
            </body>
        </html>
    );
}
